In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../Data/errors.csv')
df.head()

              datetime  machineID errorID
0  2015-01-03 07:00:00          1  error1
1  2015-01-03 20:00:00          1  error3
2  2015-01-04 06:00:00          1  error5
3  2015-01-10 15:00:00          1  error4
4  2015-01-22 10:00:00          1  error4

In [2]:
from dateutil import parser

df['datetime'] = df['datetime'].apply(
    lambda x: parser.parse(x) if pd.notnull(x) else None
)

print(df.dtypes)
df.head()

datetime     datetime64[ns]
machineID             int64
errorID              object
dtype: object

             datetime  machineID errorID
0 2015-01-03 07:00:00          1  error1
1 2015-01-03 20:00:00          1  error3
2 2015-01-04 06:00:00          1  error5
3 2015-01-10 15:00:00          1  error4
4 2015-01-22 10:00:00          1  error4

In [3]:
print(df.shape)     
print(df.dtypes)      
print(df.isnull().sum()) 
print(df.describe())
df.duplicated().sum()

(3919, 3)
datetime     datetime64[ns]
machineID             int64
errorID              object
dtype: object
datetime     0
machineID    0
errorID      0
dtype: int64
                            datetime    machineID
count                           3919  3919.000000
mean   2015-07-01 03:34:18.586374144    51.044654
min              2015-01-01 06:00:00     1.000000
25%              2015-03-31 05:00:00    25.000000
50%              2015-07-01 06:00:00    51.000000
75%              2015-10-01 15:00:00    77.000000
max              2016-01-01 05:00:00   100.000000
std                              NaN    28.954988

np.int64(0)