In [33]:
import pandas as pd

In [34]:
df = pd.read_csv('../Data/FullDataSet.csv')
df.head()

       errors_datetime  errors_machineID errors_errorID    failures_datetime  failures_machineID failures_failure failures_features_datetime  failures_features_machineID failures_features_failure  failures_features_failure_comp1  failures_features_failure_comp2  failures_features_failure_comp3  failures_features_failure_comp4  failures_features_days_since_last_failure  failures_features_cumulative_failures  failures_features_hour  failures_features_dayofweek  failures_features_month  failures_features_quarter  failures_features_is_weekend  machines_machineID machines_model  machines_age       maint_datetime  maint_machineID maint_comp   telemetry_datetime  telemetry_machineID  telemetry_volt  telemetry_rotate  telemetry_pressure  telemetry_vibration
0  2015-01-03 07:00:00                 1         error1  2015-01-05 06:00:00                   1            comp4        2015-01-05 06:00:00                            1                     comp4                            False                            False                            False                             True                                        NaN                                      1                       6                            0                        1                          1                             0                   1         model3            18  2014-06-01 06:00:00                1      comp2  2015-01-01 06:00:00                    1      176.217853        418.504078          113.077935            45.087686
1  2015-01-03 20:00:00                 1         error3  2015-03-06 06:00:00                   1            comp1        2015-03-06 06:00:00                            1                     comp1                             True                            False                            False                            False                                       60.0                                      2                       6                            4                        3                          1                             0                   2         model4             7  2014-07-16 06:00:00                1      comp4  2015-01-01 07:00:00                    1      162.879223        402.747490           95.460525            43.413973
2  2015-01-04 06:00:00                 1         error5  2015-04-20 06:00:00                   1            comp2        2015-04-20 06:00:00                            1                     comp2                            False                             True                            False                            False                                       45.0                                      3                       6                            0                        4                          2                             0                   3         model3             8  2014-07-31 06:00:00                1      comp3  2015-01-01 08:00:00                    1      170.989902        527.349825           75.237905            34.178847
3  2015-01-10 15:00:00                 1         error4  2015-06-19 06:00:00                   1            comp4        2015-06-19 06:00:00                            1                     comp4                            False                            False                            False                             True                                       60.0                                      4                       6                            4                        6                          2                             0                   4         model3             7  2014-12-13 06:00:00                1      comp1  2015-01-01 09:00:00                    1      162.462833        346.149335          109.248561            41.122144
4  2015-01-22 10:00:00                 1         error4  2015-09-02 06:00:00                   1            comp4        2015-09-02 06:00:00                            1                     comp4                            False                            False                            False                             True                                       75.0                                      5                       6                            2                        9                          3                             0                   5         model3             2  2015-01-05 06:00:00                1      comp4  2015-01-01 10:00:00                    1      157.610021        435.376873          111.886648            25.990511

In [35]:
df.columns

Index(['errors_datetime', 'errors_machineID', 'errors_errorID',
       'failures_datetime', 'failures_machineID', 'failures_failure',
       'failures_features_datetime', 'failures_features_machineID',
       'failures_features_failure', 'failures_features_failure_comp1',
       'failures_features_failure_comp2', 'failures_features_failure_comp3',
       'failures_features_failure_comp4',
       'failures_features_days_since_last_failure',
       'failures_features_cumulative_failures', 'failures_features_hour',
       'failures_features_dayofweek', 'failures_features_month',
       'failures_features_quarter', 'failures_features_is_weekend',
       'machines_machineID', 'machines_model', 'machines_age',
       'maint_datetime', 'maint_machineID', 'maint_comp', 'telemetry_datetime',
       'telemetry_machineID', 'telemetry_volt', 'telemetry_rotate',
       'telemetry_pressure', 'telemetry_vibration'],
      dtype='object')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 876100 entries, 0 to 876099
Data columns (total 32 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   errors_datetime                            876100 non-null  object
 1   errors_machineID                           876100 non-null  int64
 2   errors_errorID                             876100 non-null  object
 3   failures_datetime                          876100 non-null  object
 4   failures_machineID                         876100 non-null  int64
 5   failures_failure                           876100 non-null  object
 6   failures_features_datetime                 876100 non-null  object
 7   failures_features_machineID                876100 non-null  int64
 8   failures_features_failure                  876100 non-null  object
 9   failures_features_failure_comp1            876100 non-null  bool
 10  failures_features_failure_comp2            876100 non-null  bool
 11  failures_features_failure_comp3            876100 non-null  bool
 12  failures_features_failure_comp4            876100 non-null  bool
 13  failures_features_days_since_last_failure  763279 non-null  float64
 14  failures_features_cumulative_failures      876100 non-null  int64
 15  failures_features_hour                     876100 non-null  int64
 16  failures_features_dayofweek                876100 non-null  int64
 17  failures_features_month                    876100 non-null  int64
 18  failures_features_quarter                  876100 non-null  int64
 19  failures_features_is_weekend               876100 non-null  int64
 20  machines_machineID                         876100 non-null  int64
 21  machines_model                             876100 non-null  object
 22  machines_age                               876100 non-null  int64
 23  maint_datetime                             876100 non-null  object
 24  maint_machineID                            876100 non-null  int64
 25  maint_comp                                 876100 non-null  object
 26  telemetry_datetime                         876100 non-null  object
 27  telemetry_machineID                        876100 non-null  int64
 28  telemetry_volt                             876100 non-null  float64
 29  telemetry_rotate                           876100 non-null  float64
 30  telemetry_pressure                         876100 non-null  float64
 31  telemetry_vibration                        876100 non-null  float64
dtypes: bool(4), float64(5), int64(13), object(10)
memory usage: 190.5+ MB

In [37]:
df.isnull().sum().sort_values(ascending=False)

failures_features_days_since_last_failure    112821
errors_datetime                                   0
failures_features_month                           0
telemetry_pressure                                0
telemetry_rotate                                  0
telemetry_volt                                    0
telemetry_machineID                               0
telemetry_datetime                                0
maint_comp                                        0
maint_machineID                                   0
maint_datetime                                    0
machines_age                                      0
machines_model                                    0
machines_machineID                                0
failures_features_is_weekend                      0
failures_features_quarter                         0
failures_features_dayofweek                       0
errors_machineID                                  0
failures_features_hour                            0
failures_features_cumulative_failures             0
failures_features_failure_comp4                   0
failures_features_failure_comp3                   0
failures_features_failure_comp2                   0
failures_features_failure_comp1                   0
failures_features_failure                         0
failures_features_machineID                       0
failures_features_datetime                        0
failures_failure                                  0
failures_machineID                                0
failures_datetime                                 0
errors_errorID                                    0
telemetry_vibration                               0
dtype: int64

In [41]:
df['failures_features_days_since_last_failure'] = \
    df['failures_features_days_since_last_failure'].fillna(-1)
df['has_failure_before'] = df['failures_features_days_since_last_failure'].apply(lambda x: 0 if x == -1 else 1)
df['has_failure_before'] = df['has_failure_before'].astype(bool)

In [42]:
df.head()

       errors_datetime  errors_machineID errors_errorID    failures_datetime  failures_machineID failures_failure failures_features_datetime  failures_features_machineID failures_features_failure  failures_features_failure_comp1  failures_features_failure_comp2  failures_features_failure_comp3  failures_features_failure_comp4  failures_features_days_since_last_failure  failures_features_cumulative_failures  failures_features_hour  failures_features_dayofweek  failures_features_month  failures_features_quarter  failures_features_is_weekend  machines_machineID machines_model  machines_age       maint_datetime  maint_machineID maint_comp   telemetry_datetime  telemetry_machineID  telemetry_volt  telemetry_rotate  telemetry_pressure  telemetry_vibration  has_failure_before
0  2015-01-03 07:00:00                 1         error1  2015-01-05 06:00:00                   1            comp4        2015-01-05 06:00:00                            1                     comp4                            False                            False                            False                             True                                       -1.0                                      1                       6                            0                        1                          1                             0                   1         model3            18  2014-06-01 06:00:00                1      comp2  2015-01-01 06:00:00                    1      176.217853        418.504078          113.077935            45.087686               False
1  2015-01-03 20:00:00                 1         error3  2015-03-06 06:00:00                   1            comp1        2015-03-06 06:00:00                            1                     comp1                             True                            False                            False                            False                                       60.0                                      2                       6                            4                        3                          1                             0                   2         model4             7  2014-07-16 06:00:00                1      comp4  2015-01-01 07:00:00                    1      162.879223        402.747490           95.460525            43.413973                True
2  2015-01-04 06:00:00                 1         error5  2015-04-20 06:00:00                   1            comp2        2015-04-20 06:00:00                            1                     comp2                            False                             True                            False                            False                                       45.0                                      3                       6                            0                        4                          2                             0                   3         model3             8  2014-07-31 06:00:00                1      comp3  2015-01-01 08:00:00                    1      170.989902        527.349825           75.237905            34.178847                True
3  2015-01-10 15:00:00                 1         error4  2015-06-19 06:00:00                   1            comp4        2015-06-19 06:00:00                            1                     comp4                            False                            False                            False                             True                                       60.0                                      4                       6                            4                        6                          2                             0                   4         model3             7  2014-12-13 06:00:00                1      comp1  2015-01-01 09:00:00                    1      162.462833        346.149335          109.248561            41.122144                True
4  2015-01-22 10:00:00                 1         error4  2015-09-02 06:00:00                   1            comp4        2015-09-02 06:00:00                            1                     comp4                            False                            False                            False                             True                                       75.0                                      5                       6                            2                        9                          3                             0                   5         model3             2  2015-01-05 06:00:00                1      comp4  2015-01-01 10:00:00                    1      157.610021        435.376873          111.886648            25.990511                True