In [1]:
import pandas as pd
df = pd.read_csv("machines.csv")
df.head()

   machineID   model  age
0          1  model3   18
1          2  model4    7
2          3  model3    8
3          4  model3    7
4          5  model3    2

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   machineID  100 non-null    int64
 1   model      100 non-null    object
 2   age        100 non-null    int64
dtypes: int64(2), object(1)
memory usage: 2.5+ KB

In [3]:
df.isnull().sum()

machineID    0
model        0
age          0
dtype: int64

In [4]:
df['model'].value_counts()

model
model3    35
model4    32
model2    17
model1    16
Name: count, dtype: int64

In [5]:
df = pd.get_dummies(df,drop_first=True,dtype=int)

In [6]:
df.head()

   machineID  age  model_model2  model_model3  model_model4
0          1   18             0             1             0
1          2    7             0             0             1
2          3    8             0             1             0
3          4    7             0             1             0
4          5    2             0             1             0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   machineID     100 non-null    int64
 1   age           100 non-null    int64
 2   model_model2  100 non-null    int64
 3   model_model3  100 non-null    int64
 4   model_model4  100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB